import Link from 'next/link';
import { Abel } from 'next/font/google';
import './styles.css';
import './globals.css';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

const abel = Abel({
	style: ['normal'],
	weight: ['400'],
	subsets: ['latin'],
});

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body className={`${abel.className} bg-gray-800 text-white p-4`}>
				<nav className="p-2">
					<ul className="flex gap-3 justify-center pr-3 ">
						<li>
							<Link href="/" style={{ color: '#fff' }}>
								Home
							</Link>
						</li>
						<li>
							<Link href="/about" style={{ color: '#fff' }}>
								About
							</Link>
						</li>
						<li>
							<Link href="/posts" style={{ color: '#fff' }}>
								Posts
							</Link>
						</li>
					</ul>
				</nav>

				{children}
			</body>
		</html>
	);
}
