import Link from "next/link";
import { Abel } from "next/font/google";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const abel = Abel({
	style: ["normal"],
	weight: ["400"],
	subsets: ["latin"],
});

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body
				className={abel.className}
				style={{
					background: "rgb(40,40,40)",
					color: "#fff",
					padding: "1em",
				}}
			>
				<nav>
					<ul
						style={{
							display: "flex",
							gap: "1em",
							listStyle: "none",
						}}
					>
						<li>
							<Link href="/" style={{ color: "#fff" }}>
								Home
							</Link>
						</li>
						<li>
							<Link href="/about" style={{ color: "#fff" }}>
								About
							</Link>
						</li>
						<li>
							<Link href="/posts" style={{ color: "#fff" }}>
								Posts
							</Link>
						</li>
					</ul>
				</nav>

				{children}
			</body>
		</html>
	);
}
