import Link from 'next/link';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body>
				<nav>
					<ul style={{ display: 'flex', gap: '1em' }}>
						<li>
							<Link href="/">Home</Link>
						</li>
						<li>
							<Link href="/about">About</Link>
						</li>
					</ul>
				</nav>

				{children}
			</body>
		</html>
	);
}
