import { Abel } from 'next/font/google';
import './styles.css';
import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

const abel = Abel({
	style: ['normal'],
	weight: ['400'],
	subsets: ['latin'],
});

export default function RootLayout({ children }) {
	return (
		<html lang='es'>
			<body
				className={`${abel.className}  m-auto max-w-screen-xl bg-gray-800 text-white`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
